# Generated by Django 4.0 on 2022-12-14 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_likes_alter_user_influencers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='post_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
