# Generated by Django 4.0 on 2023-01-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
