# Generated by Django 4.0 on 2023-01-22 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_user_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='influencers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
